name: Test in Docker
on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:latest
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install
      
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
          install: false
          config-file: cypress.prod.config.js
      
      - name: Save report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: mochawesome-report
        if: always()